name: Deploy Backend to EC2

on:
  push:
    branches:
      - main   # deploy only when pushing to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy Backend to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            # Create app directory if not exists
            mkdir -p ~/backend

            # Go to backend directory
            cd ~/backend

            # Initialize repo if not already
            if [ ! -d ".git" ]; then
              git init
              git remote add origin git@github.com:${{ github.repository }}.git
            fi

            # Fetch latest backend only
            git fetch origin main
            git reset --hard origin/main
            cd backend

            # Install dependencies & build
            npm install
            npx prisma generate

            # Restart with PM2
            pm2 restart backend || pm2 start npm --name backend -- run start
          EOF
